title: John Kuo
email: davidkoojohn@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is davidkoojohn blog.
baseurl: "/share/"
url: ""
author:
  name: John Kuo
  twitter: davidkoojohn
  picture: //assets/davidkoojohn.jpg
twitter_username:
github_username:
logo: /assets/davidkoojohn.jpg
twitter_username: davidkoojohn
github_username:  davidkoojohn

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
remote_theme: mmistakes/jekyll-theme-basically-basic
plugins:
  - jekyll-feed

# https://github.com/ashemenev/ashemenev.github.io/blob/master/index.html
paginate: 5  # amount of posts to show per page
paginate_path: /page:num/

search: true
