title: KooJohn`s
email: davidkoojohn@gmail.com
description: >-
  my life is my life; to be or not to be.
baseurl: "/share/"
url: ""
twitter_username: davidkoojohn
github_username:  davidkoojohn

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed



