title: John Kuo
email: davidkoojohn@gmail.com
description: 我梦寐以求是真爱和自由．
baseurl: "/share/"
url: ""
twitter_username: davidkoojohn
github_username:  davidkoojohn

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
#remote_theme: "mmistakes/jekyll-theme-basically-basic"

plugins:
  - jekyll-feed


