title: John Kuo
email: davidkoojohn@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is davidkoojohn blog.
baseurl: "/share/"
url: ""
author:
  name: Kuo
  twitter: davidkoojohn
  picture:
twitter_username:
github_username:
logo: "/assets/davidkoojohn.jpg"
twitter_username: davidkoojohn
github_username:  davidkoojohn

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
remote_theme: "mmistakes/jekyll-theme-basically-basic"
plugins:
  - jekyll-feed

